### ISSUE TITLE
PUAM constituent EndDates in the FUTURE, and equal to BeginDate

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#39]
http://data.americanartcollaborative.org/page/puam/constituent/12816, for example, appears to have died in 2100.  This is probably some sort of placeholder value, and should be handled as such.

**Comment by VladimirAlexiev** [comment]
The source ("ConstituentID":12816) has
```
"EndDate":2100,
"EndDateISO":null,
```
So maybe you should use `EndDateISO` instead of `EndDate`. On the other hand, `EndDateISO` has trailing spaces: I think it's formatted as `YYYY______` or `YYYY-MM___` or `YYYY-MM-DD`.

Also, ignore EndDate that is equal to BeginDate, eg see
```
"ConstituentID":93,
"DisplayDate":"American, born 1947",
"BeginDate":1947,
"EndDate":1947,
```
@kateblanch Is it possible for the PUAM person to clean up some of this cruft, rather than @bsnikhila having to code a bunch of workarounds in the mapping?

**Comment by cathryng** [comment]
where did we leave off with this?  we are happy to clean up the data, but need to know what you want - null value?

**Comment by VladimirAlexiev** [comment]
Yes: rather than making EndDate in the future or equal to BeginDate, leave it null or missing

**Comment by cathryng** [comment]
i will null these dates in the data refresh -
